/**
 * This file is generated by Fork CMS, it contains
 * the links that can be used by the editor
 * 
 * Fork CMS
 * @generated	2013-02-23 23:07:04
 */

// init var
var linkList = [["Home","\/"],["Blog","\/blog"],["About us","\/about-us"],["About us > Location","\/about-us\/location"],["About us > About us","\/about-us\/about-us"],["History","\/history"],["FAQ","\/faq"],["Instagram","\/instagram"],["Sitemap","\/sitemap"],["Disclaimer","\/disclaimer"],["404","\/404"],["Lorem ipsum","\/lorem-ipsum"],["Search","\/search"],["Tags","\/tags"]];