<?php

/**
 * This file is generated by Fork CMS, it contains
 * the mapping between a pageID and the URL
 * 
 * Fork CMS
 * @generated	2013-02-23 23:07:04
 */

// init var
$keys = array();

$keys[1] = '';
$keys[404] = '404';
$keys[406] = 'about-us';
$keys[408] = 'about-us/about-us';
$keys[407] = 'about-us/location';
$keys[405] = 'blog';
$keys[3] = 'disclaimer';
$keys[413] = 'faq';
$keys[409] = 'history';
$keys[415] = 'instagram';
$keys[410] = 'lorem-ipsum';
$keys[411] = 'search';
$keys[2] = 'sitemap';
$keys[412] = 'tags';

?>