<?php

/**
 * This file is generated by Fork CMS, it contains
 * more information about the page-structure
 * 
 * Fork CMS
 * @generated	2013-02-23 23:07:04
 */

// init var
$navigation = array();

$navigation['footer'][0][2]['page_id'] = 2;
$navigation['footer'][0][2]['url'] = 'sitemap';
$navigation['footer'][0][2]['full_url'] = 'sitemap';
$navigation['footer'][0][2]['title'] = 'Sitemap';
$navigation['footer'][0][2]['navigation_title'] = 'Sitemap';
$navigation['footer'][0][2]['has_extra'] = false;
$navigation['footer'][0][2]['no_follow'] = false;
$navigation['footer'][0][2]['hidden'] = false;
$navigation['footer'][0][2]['extra_blocks'] = null;
$navigation['footer'][0][2]['tree_type'] = 'sitemap';

$navigation['footer'][0][3]['page_id'] = 3;
$navigation['footer'][0][3]['url'] = 'disclaimer';
$navigation['footer'][0][3]['full_url'] = 'disclaimer';
$navigation['footer'][0][3]['title'] = 'Disclaimer';
$navigation['footer'][0][3]['navigation_title'] = 'Disclaimer';
$navigation['footer'][0][3]['has_extra'] = false;
$navigation['footer'][0][3]['no_follow'] = true;
$navigation['footer'][0][3]['hidden'] = false;
$navigation['footer'][0][3]['extra_blocks'] = null;
$navigation['footer'][0][3]['tree_type'] = 'page';

$navigation['root'][0][404]['page_id'] = 404;
$navigation['root'][0][404]['url'] = '404';
$navigation['root'][0][404]['full_url'] = '404';
$navigation['root'][0][404]['title'] = '404';
$navigation['root'][0][404]['navigation_title'] = '404';
$navigation['root'][0][404]['has_extra'] = false;
$navigation['root'][0][404]['no_follow'] = false;
$navigation['root'][0][404]['hidden'] = false;
$navigation['root'][0][404]['extra_blocks'] = null;
$navigation['root'][0][404]['tree_type'] = 'error';

$navigation['root'][0][410]['page_id'] = 410;
$navigation['root'][0][410]['url'] = 'lorem-ipsum';
$navigation['root'][0][410]['full_url'] = 'lorem-ipsum';
$navigation['root'][0][410]['title'] = 'Lorem ipsum';
$navigation['root'][0][410]['navigation_title'] = 'Lorem ipsum';
$navigation['root'][0][410]['has_extra'] = false;
$navigation['root'][0][410]['no_follow'] = true;
$navigation['root'][0][410]['hidden'] = true;
$navigation['root'][0][410]['extra_blocks'] = null;
$navigation['root'][0][410]['tree_type'] = 'hidden';

$navigation['root'][0][411]['page_id'] = 411;
$navigation['root'][0][411]['url'] = 'search';
$navigation['root'][0][411]['full_url'] = 'search';
$navigation['root'][0][411]['title'] = 'Search';
$navigation['root'][0][411]['navigation_title'] = 'Search';
$navigation['root'][0][411]['has_extra'] = true;
$navigation['root'][0][411]['no_follow'] = false;
$navigation['root'][0][411]['hidden'] = false;
$navigation['root'][0][411]['extra_blocks'] = array(array('id' => 12, 'module' => 'search', 'action' => null));
$navigation['root'][0][411]['tree_type'] = 'page';

$navigation['root'][0][412]['page_id'] = 412;
$navigation['root'][0][412]['url'] = 'tags';
$navigation['root'][0][412]['full_url'] = 'tags';
$navigation['root'][0][412]['title'] = 'Tags';
$navigation['root'][0][412]['navigation_title'] = 'Tags';
$navigation['root'][0][412]['has_extra'] = true;
$navigation['root'][0][412]['no_follow'] = false;
$navigation['root'][0][412]['hidden'] = false;
$navigation['root'][0][412]['extra_blocks'] = array(array('id' => 13, 'module' => 'tags', 'action' => null));
$navigation['root'][0][412]['tree_type'] = 'page';

$navigation['page'][0][1]['page_id'] = 1;
$navigation['page'][0][1]['url'] = '';
$navigation['page'][0][1]['full_url'] = '';
$navigation['page'][0][1]['title'] = 'Home';
$navigation['page'][0][1]['navigation_title'] = 'Home';
$navigation['page'][0][1]['has_extra'] = false;
$navigation['page'][0][1]['no_follow'] = false;
$navigation['page'][0][1]['hidden'] = false;
$navigation['page'][0][1]['extra_blocks'] = null;
$navigation['page'][0][1]['tree_type'] = 'home';

$navigation['page'][1][405]['page_id'] = 405;
$navigation['page'][1][405]['url'] = 'blog';
$navigation['page'][1][405]['full_url'] = 'blog';
$navigation['page'][1][405]['title'] = 'Blog';
$navigation['page'][1][405]['navigation_title'] = 'Blog';
$navigation['page'][1][405]['has_extra'] = true;
$navigation['page'][1][405]['no_follow'] = false;
$navigation['page'][1][405]['hidden'] = false;
$navigation['page'][1][405]['extra_blocks'] = array(array('id' => 6, 'module' => 'blog', 'action' => null));
$navigation['page'][1][405]['tree_type'] = 'page';

$navigation['page'][1][406]['page_id'] = 406;
$navigation['page'][1][406]['url'] = 'about-us';
$navigation['page'][1][406]['full_url'] = 'about-us';
$navigation['page'][1][406]['title'] = 'About us';
$navigation['page'][1][406]['navigation_title'] = 'About us';
$navigation['page'][1][406]['has_extra'] = false;
$navigation['page'][1][406]['no_follow'] = false;
$navigation['page'][1][406]['hidden'] = false;
$navigation['page'][1][406]['extra_blocks'] = null;
$navigation['page'][1][406]['tree_type'] = 'page';

$navigation['page'][1][409]['page_id'] = 409;
$navigation['page'][1][409]['url'] = 'history';
$navigation['page'][1][409]['full_url'] = 'history';
$navigation['page'][1][409]['title'] = 'History';
$navigation['page'][1][409]['navigation_title'] = 'History';
$navigation['page'][1][409]['has_extra'] = false;
$navigation['page'][1][409]['no_follow'] = false;
$navigation['page'][1][409]['hidden'] = false;
$navigation['page'][1][409]['extra_blocks'] = null;
$navigation['page'][1][409]['tree_type'] = 'page';

$navigation['page'][1][413]['page_id'] = 413;
$navigation['page'][1][413]['url'] = 'faq';
$navigation['page'][1][413]['full_url'] = 'faq';
$navigation['page'][1][413]['title'] = 'FAQ';
$navigation['page'][1][413]['navigation_title'] = 'FAQ';
$navigation['page'][1][413]['has_extra'] = true;
$navigation['page'][1][413]['no_follow'] = false;
$navigation['page'][1][413]['hidden'] = false;
$navigation['page'][1][413]['extra_blocks'] = array(array('id' => 16, 'module' => 'faq', 'action' => null));
$navigation['page'][1][413]['tree_type'] = 'page';

$navigation['page'][1][415]['page_id'] = 415;
$navigation['page'][1][415]['url'] = 'instagram';
$navigation['page'][1][415]['full_url'] = 'instagram';
$navigation['page'][1][415]['title'] = 'Instagram';
$navigation['page'][1][415]['navigation_title'] = 'Instagram';
$navigation['page'][1][415]['has_extra'] = true;
$navigation['page'][1][415]['no_follow'] = false;
$navigation['page'][1][415]['hidden'] = false;
$navigation['page'][1][415]['extra_blocks'] = array(array('id' => 19, 'module' => 'instagram', 'action' => null));
$navigation['page'][1][415]['tree_type'] = 'page';

$navigation['page'][406][407]['page_id'] = 407;
$navigation['page'][406][407]['url'] = 'location';
$navigation['page'][406][407]['full_url'] = 'about-us/location';
$navigation['page'][406][407]['title'] = 'Location';
$navigation['page'][406][407]['navigation_title'] = 'Location';
$navigation['page'][406][407]['has_extra'] = false;
$navigation['page'][406][407]['no_follow'] = false;
$navigation['page'][406][407]['hidden'] = false;
$navigation['page'][406][407]['extra_blocks'] = null;
$navigation['page'][406][407]['tree_type'] = 'page';

$navigation['page'][406][408]['page_id'] = 408;
$navigation['page'][406][408]['url'] = 'about-us';
$navigation['page'][406][408]['full_url'] = 'about-us/about-us';
$navigation['page'][406][408]['title'] = 'About us';
$navigation['page'][406][408]['navigation_title'] = 'About us';
$navigation['page'][406][408]['has_extra'] = false;
$navigation['page'][406][408]['no_follow'] = false;
$navigation['page'][406][408]['hidden'] = false;
$navigation['page'][406][408]['extra_blocks'] = null;
$navigation['page'][406][408]['tree_type'] = 'page';

?>